import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class BffService {
  private apiUrl = 'http://localhost:9001/bff/conector/exercises/with-images';
  private token = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJYM191NGQ4LVRVY0t0WERDTU01UmR3dzkzdi16M3NTek9qOVdKaXlRandzIn0.eyJleHAiOjE3MzQ1NjI0NTYsImlhdCI6MTczNDU1ODg1NiwianRpIjoiMzUyMTY0OWYtYzcwNi00ZDI4LWJhMzgtZmVkZjFkOGVkY2I2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOlsiZGFjcy1yZWFsbSIsIm1hc3Rlci1yZWFsbSIsImFjY291bnQiXSwic3ViIjoiYzIwODE1MWUtOTM4Mi00MDE4LTg5YjYtMGMyYzc4MmExNWQ4IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZGFjczIwMjMtYmZmIiwic2Vzc2lvbl9zdGF0ZSI6IjkwMTM3YjBkLTI1MjQtNDJmNi04YTU0LWJiYWU1NDVhOTdmYSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiLCJodHRwOi8vbG9jYWxob3N0OjQyMDAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImNyZWF0ZS1yZWFsbSIsImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiZGFjcy1yZWFsbSI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiI5MDEzN2IwZC0yNTI0LTQyZjYtOGE1NC1iYmFlNTQ1YTk3ZmEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.MgtaF3j9JrjsXMHqRBlrvpkYVrJE292GAi_n-tPxTTmsOfoHXRBdTnv24JGdMXjl_mond19D5U7jPOxjaZc1KLOnvQWY3RPwNJx89wHFhIGLgnIaKmGbcFWu73tr5VipsU5kz0wq1ea9lOTkzqZh3lsegKu0IcHoD4IGD__e1G-IyncAfpsBj8LdVbMy-QsMx3vn2WhIAbogiJm7NwlvuGa-z7hlM-abnd--eBCe3jz1qd-6IGV70dRprjALBu70WmbOBHHRjPH1_7EKeFmSg6wxWjzESOC39ofux-E60EoRFuQYkjRVgRkYoUMTVf0PR_zobEWSZEbFLi2Eab8pbg'; // Token manual para pruebas

  constructor(private http: HttpClient) {}

  // Método para obtener datos desde el BFF
  getDatos(): Observable<any> {
    const headers = new HttpHeaders().set('Authorization', `Bearer ${this.token}`);
    console.log('Realizando solicitud a:', this.apiUrl);
    console.log('Encabezados de la solicitud:', headers);

    return this.http.get<any>(this.apiUrl, { headers });
  }
}
