// bff.service.ts
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders} from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class BffService {

  private apiUrl = 'http://localhost:9001/bff/conector/exercises/with-images';
  private token = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJYM191NGQ4LVRVY0t0WERDTU01UmR3dzkzdi16M3NTek9qOVdKaXlRandzIn0.eyJleHAiOjE3MzQzOTI1MDQsImlhdCI6MTczNDM4ODkwNCwianRpIjoiMGRkOWVjZjItNTkyYS00MGJjLThjNjEtMDRiN2VjN2M3MmQzIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOlsiZGFjcy1yZWFsbSIsIm1hc3Rlci1yZWFsbSIsImFjY291bnQiXSwic3ViIjoiYzIwODE1MWUtOTM4Mi00MDE4LTg5YjYtMGMyYzc4MmExNWQ4IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZGFjczIwMjMtYmZmIiwic2Vzc2lvbl9zdGF0ZSI6IjU1ZjY4NjJiLTYwYjYtNGQ5NS04MGY1LWEwNzUxYmM0YTZjNiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImNyZWF0ZS1yZWFsbSIsImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiZGFjcy1yZWFsbSI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiI1NWY2ODYyYi02MGI2LTRkOTUtODBmNS1hMDc1MWJjNGE2YzYiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.n8amWcwekH5uRPAdqCs05XojOwWoKwo2Rr5WrNdf2N2VtumM5dHqXs0QoWpX2xKKyRwOvTlXUPArn9tk9t7rrD9TeHa_cZVVMJkX5yLZ44vpwI8wCW2C0EpKqzfRlDuSyNMfUIzCxT7CfhDPeDVfwAtrao5yfavF1ZCZYDy_cexG_4fIXuMaIty07MI6LJWBi4LtGvLoWTpt2LLiUKMDbkb6BlaZX1Vfsrs8rHlJpMu2pVdDC4Ch54GUPwrTN4FYpsYjBP2HCbzPI-UjknOSkFlHrnrtgUg7dBr43vdzbR_QRIFFWH5HPjjfyxPYNT1aumPzqAbGwur8_OZbQMtYvQ' ; // Agrega tu token aquí manualmente

  constructor(private http: HttpClient) { }

  // Método para obtener los datos desde el BFF
  getDatos(): Observable<any> {
    const headers = new HttpHeaders().set('Authorization', `Bearer ${this.token}`);
    return this.http.get<any>(this.apiUrl, { headers });
  }
}
